### PR TITLE
Fix version check for cases where no version with a certain tag was published

### PR DESCRIPTION
**Pull request by RubenVerborgh**
npm gives empty output when no version for a certain tag is published:

```
$ npm view underscore@whatever

```

This PR takes that into account.

Closes https://github.com/JS-DevTools/npm-publish/issues/24

### CODE REVIEW

**Review by idev1990 — APPROVED** [review]

**Comment by JamesMessinger** [comment]
I believe this PR is no longer needed because #19 solves the same issue.  Please let me know if that's not the case.

**Comment by RubenVerborgh** [comment]
@JamesMessinger It does not. #19 does not check for empty `stdout`.

**Comment by JamesMessinger** [comment]
ah, ok.  Thanks for clarifying that.  I'll fix that really quick and release an updated version

**Comment by JamesMessinger** [comment]
Ok, this is fixed now.  Released as v1.4.2

**Pull request closed without merging**
