### PR TITLE
Fix initial package publishing, once again

### LINKED ISSUE #11: Initial publish
Hello! Thanks for the great action.

I noticed it always fails saying

```
##[error]Error: Unable to determine the current version of @pkg/NAME on NPM. 
```

...when you do a first publish of the package (when you're just starting a repository). You need to manually push the first version, and then it will work.

Is it intended or can be fixed? I guess we can add an error handler [here](https://github.com/JS-DevTools/npm-publish/blob/5a905d14c6937160fd0bda31111bacb56c24c400/src/npm-publish.ts#L16).

Thank you.

### PR DESCRIPTION
**Pull request by ZitRos**
See #14 for more details. Thanks @varunsridharan for reporting, and I also encountered this bug myself.

Fixes wrong #12 to fix #11 once again.

### CODE REVIEW

**Comment by IdanAdar** [comment]
I think this fix is needed. I cannot publish my package using this action.

**Comment by ZitRos** [comment]
Ping @JamesMessinger, please merge ^^

**Comment by JamesMessinger** [comment]
Sorry it took me so long to merge this.  I've been swamped at work 😰

**Comment by ZitRos** [comment]
Thank you James! Happy holidays!

**Pull request merged**
